changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - octocat
  categories:
    - title: 'Features'
      labels:
        - feature
        - enhancement
    - title: 'Bug Fixes'
      labels:
        - bug
        - fix
    - title: 'Documentation'
      labels:
        - documentation
    - title: 'Internal'
      labels:
        - internal
        - chore
    - title: 'Tests'
      labels:
        - test
    - title: 'Other Changes'
      labels:
        - '*'
